version: "3.9"

services:

  db:
    image: mysql:8.0
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: proyectointermodular
      MYSQL_DATABASE: proyectointermodular
      MYSQL_USER: proyectointermodular
      MYSQL_PASSWORD: proyectointermodular

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  backend:
    build: .

    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_USER: proyectointermodular
      DB_PASSWORD: proyectointermodular
      DB_NAME: proyectointermodular

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: proyectointermodular
      UPLOAD_LIMIT: 256M
    depends_on:
      - db

volumes:
  mysql_data: